networks:
  default:
    ipam:
      config:
      - gateway: 172.28.0.1
        subnet: 172.28.0.0/16
      driver: default
services:
  openuav_turtlebot:
    build: dockerfiles/openuav_sample/
    devices:
    - /dev/nvidia0
    - /dev/nvidia1
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    - /dev/nvidia-uvm-tools
    entrypoint: /home/setup.sh
    environment:
    - DISPLAY=$DISPLAY
    expose:
    - '8000'
    - '31819'
    - '80'
    - '9090'
    volumes:
    - ../samples/testSimulation:/simulation
    - /tmp/.X11-unix:/tmp/.X11-unix
    - nvidia_driver_390.30:/usr/local/nvidia:ro
version: '2'
volumes:
  nvidia_driver_390.30:
    external: true
